EPI_Data_2010 <- read.csv(file.choose(), header= TRUE)
EPI<-EPI_Data_2010$EPI
plot(ecdf(EPI), do.points=FALSE, verticals= FALSE)
 help("qqnorm")
help("par")
par(pty="s")
qqnorm(EPI);qqline(EPI)
x<-seq(30,95,1)
qqplot(qt(ppoints(250),df=5),X, xlab= "Q-Q plot for t dsn")
qqline(x)
View(ppoints)
help(plot)
par(mfrow=c(2,2))
plot(ecdf(EPI),do.points=T,verticals=T, col="dark gray")
par(pty="s")
qqnorm(EPI_Data_2010$EPI)
help("par")

plot(ecdf(EPI_Data_2010$Population07), do.points=T, Verticals=F, col="Red")
plot(ecdf(EPI_Data_2010$DALY), do.points=T, Verticals=F, col="Orange")
qqnorm(EPI_Data_2010$Landarea)

EPIdata<-ggplot(EPI_Data_2010$DALY,EPI_Data_2010$)
library(ggplot2)
ggplot(EPI_Data_2010, aes(x="x", y="y"))+geom_boxplot(outlier.color = "grey", outlier.shape=15,)
